puts "Marquin".object_id
puts "Marquin".object_id
puts "Marquin".object_id
puts "Marquin".object_id
puts "Marquin".object_id
puts "=========================="
puts :Marquin.object_id
puts :Marquin.object_id
puts :Marquin.object_id
puts :Marquin.object_id
puts :Marquin.object_id